language: clojure
lein: lein2
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zlib1g-dev
install:
  - git clone https://github.com/chrovis/libbwa.git
  - mkdir -p libbwa/build
  - cd libbwa/build
  - cmake
  - make && make install
script: lein2 midje
